#!/bin/bash

# raw lease dump file directories
FILES=../../CLAM/leases/poly_all/128blocks_128ways/*
OUT=./output


# path to python processing script
PATHTEMP=gen_lease_src.py
OPTIONS="-n 128 -b 9 -m 65520"

# process
for f in $FILES
do
filename=$(basename -- "$f") 		# get filename+ext without path
  filename="${filename%.*}" 		# get just filename
  python $PATHTEMP -i $f $OPTIONS -o $OUT/${filename}.c
done
for f in $OUT/*; do
  benchmark_name=$(sed 's/_[^_]*_leases.*//'<<< ${f##.*/} | sed 's/_/-/g' | sed 's/syr2d/syr2k/')
  if [[ "$f" =~ .*"fnsl" ]]; then
 	cp "$f" ../../benchmarks/poly_small_float/$benchmark_name/lease.c
  else
  	cp "$f" ../../benchmarks/poly_small_scope_float/$benchmark_name/lease_scope.c
  fi;
done 
source ~/.bash_functions
(cd ../../benchmarks/poly_small_float/ && make_benchmarks) 
(cd ../../benchmarks/poly_small_scope_float/ && make_benchmarks) 

# move resulting files to their respective folders
#cp "${OUT}/"atax* ../benchmarks/poly_small_scope/atax/lease_scope.c
#cp "${OUT}/"doitgen* ../benchmarks/poly_small_scope/doitgen/lease_scope.c
#cp "${OUT}/"floyd* ../benchmarks/poly_small_scope/floyd-warshall/lease_scope.c
#cp "${OUT}/"2mm* ../benchmarks/poly_small_scope/2mm/lease_scope.c
#cp "${OUT}/"3mm* ../benchmarks/poly_small_scope/3mm/lease_scope.c
#cp "${OUT}/"mvt* ../benchmarks/poly_small_scope/mvt/lease_scope.c
#cp "${OUT}/"nussinov* ../benchmarks/poly_small_scope/nussinov/lease_scope.c
