#!/bin/bash


# raw lease dump file directories

if [[ "$1" == "" || "$2" == "" || "$3" == "" ]]; then
	echo "must give lease lookup table size, cache size, and number of ways";
	exit 1;
fi

FILES=../../CLAM/leases/128_llt_entries/"$2"blocks_"$3"ways*/*
OUT=./output


# path to python processing script
PATHTEMP=gen_lease_src.py
OPTIONS="-n "$1" -b 9 -m 65520"

# process
for f in $FILES
do
echo $f
lease_dir="$(basename "$(dirname -- "$f")")"
filename=$(basename "$f") 
benchmark_name=$(sed 's/_[^_]*_leases.*//'<<< ${f##.*/})

python $PATHTEMP -i $f $OPTIONS -o "$OUT/$benchmark_name.c"

 	if [[ "$lease_dir" == *"C-SHEL_medium" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/C-SHEL_medium/$benchmark_name/lease_scope.c
	elif [[ "$lease_dir" == *"C-SHEL_large" ]]; then
		 cp "$OUT/${benchmark_name}.c" ../../benchmarks/C-SHEL_large/$benchmark_name/lease_scope.c
	elif [[ "$lease_dir" == *"C-SHEL_extra_large" ]]; then
		 cp "$OUT/${benchmark_name}.c" ../../benchmarks/C-SHEL_extra_large/$benchmark_name/lease_scope.c
	elif [[ "$lease_dir" == *"C-SHEL" ]]; then
		 cp "$OUT/${benchmark_name}.c" ../../benchmarks/C-SHEL/$benchmark_name/lease_scope.c
	elif [[ "$lease_dir" == *"PRL_medium" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/PRL_medium/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"PRL_large" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/PRL_large/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"PRL_extra_large" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/PRL_extra_large/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"PRL" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/PRL/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"CLAM_limited" ]]; then 
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/CLAM_limited/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"CLAM_medium" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/CLAM_medium/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"CLAM_large" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/CLAM_large/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"CLAM_extra_large" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/CLAM_extra_large/$benchmark_name/lease.c
	elif [[ "$lease_dir" == *"CLAM" ]]; then
  	 	 cp "$OUT/${benchmark_name}.c" ../../benchmarks/CLAM/$benchmark_name/lease.c
  	elif [[ "$lease_dir" == *"SHEL_medium" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/SHEL_medium/$benchmark_name/lease_scope.c
	elif [[ "$lease_dir" == *"SHEL_large" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/SHEL_large/$benchmark_name/lease_scope.c
	elif [[ "$lease_dir" == *"SHEL_extra_large" ]]; then
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/SHEL_extra_large/$benchmark_name/lease_scope.c
	else
		cp "$OUT/${benchmark_name}.c" ../../benchmarks/SHEL/$benchmark_name/lease_scope.c
	fi
done


make_benchmarks (){
variant=$(pwd |sed -n 's/.*\/\([0-9A-Za-z_]*\)/\1/p');
for i in *; do 
	if [[ "$variant" == "SHEL"* || "$variant" == "C-SHEL"* ]]; then
            if [[ -d "$i" && "$i" != "atax" && "$i" != "bicg" && "$i" != "cholesky" && "$i" != "floyd-warshall" && "$i" != "gemm" && "$i" != "gesummv" && "$i" != "gramschmidt" && "$i" != "jacobi-1d" && "$i" != "nussinov" && "$i" != "seidel-2d" && "$i" != "symm" && "$i" != "syr2k" && "$i" != "syrk" && "$i" != "trisolv" && "$i" != "trmm" && "$i" != "doitgen" && "$i" != "durbin" ]]; then
                cd  "$i" 
				rm program*
				echo "doing $i"
				make scope opt_level=O3;
				cd .. 
            fi;
   elif [[ -d "$i" ]]; then
            cd  "$i" 
			rm program*
			echo "doing $i"
			make scope opt_level=O3;
			cd .. 
   fi;
done
}



make_run_all_script () 
{ 
    variant=$(pwd |sed -n 's/.*\/\([0-9A-Za-z_]*\)/\1/p');
    script_name=run_all_"$variant".pss;
    file_path=../../fpga_proxy/scripts/;
    rm -f "$file_path"/"$script_name";
    for i in *;
    do
        if [[ "$variant" == "SHEL"* || "$variant" == "C-SHEL"* ]]; then
            if [[ -d "$i" && "$i" != "atax" && "$i" != "bicg" && "$i" != "cholesky" && "$i" != "floyd-warshall" && "$i" != "gemm" && "$i" != "gesummv" && "$i" != "gramschmidt" && "$i" != "jacobi-1d" && "$i" != "nussinov" && "$i" != "seidel-2d" && "$i" != "symm" && "$i" != "syr2k" && "$i" != "syrk" && "$i" != "trisolv" && "$i" != "trmm" && "$i" != "doitgen" && "$i" != "durbin" && "$i" != "deriche" ]]; then
                echo RUN ../benchmarks/"$variant"/"$i"/program >> "$file_path"/"$script_name";
            else
                if [[ "$i" == "deriche" && "$variant" != *"large" ]]; then
                    echo RUN ../benchmarks/"$variant"/"$i"/program >> "$file_path"/"$script_name";
                fi;
            fi;
        else
            if [[ "$i" != "deriche" || ( "$i" == "deriche" && "$variant" != *"large" ) ]]; then
                echo RUN ../benchmarks/"$variant"/"$i"/program >> "$file_path"/"$script_name";
            fi;
        fi;
    done
}



make_track_all_script () 
{ 
    variant=$(pwd |sed -n 's/.*\/\([0-9A-Za-z_]*\)/\1/p');
    script_name=track_all_"$variant".pss;
    file_path=../../fpga_proxy/scripts/;
    rm -f "$file_path"/"$script_name";
    for i in *;
    do
        if [[ "$variant" == "SHEL"* || "$variant" == "C-SHEL"* ]]; then
            if [[ -d "$i" && "$i" != "atax" && "$i" != "bicg" && "$i" != "cholesky" && "$i" != "floyd-warshall" && "$i" != "gemm" && "$i" != "gesummv" && "$i" != "gramschmidt" && "$i" != "jacobi-1d" && "$i" != "nussinov" && "$i" != "seidel-2d" && "$i" != "symm" && "$i" != "syr2k" && "$i" != "syrk" && "$i" != "trisolv" && "$i" != "trmm" && "$i" != "doitgen" && "$i" != "durbin" && "$i" != "deriche" ]]; then
                echo TRACK ../benchmarks/"$variant"/"$i"/program >> "$file_path"/"$script_name";
            else
                if [[ "$i" == "deriche" && "$variant" != *"large" ]]; then
                    echo TRACK ../benchmarks/"$variant"/"$i"/program >> "$file_path"/"$script_name";
                fi;
            fi;
        else
            if [[ "$i" != "deriche" || ( "$i" == "deriche" && "$variant" != *"large" ) ]]; then
                echo TRACK ../benchmarks/"$variant"/"$i"/program >> "$file_path"/"$script_name";
            fi;
        fi;
    done
}

make_run_all_plru_script () 
{ 
	variant=$(pwd |sed -n 's/.*\/\([0-9A-Za-z_]*\)/\1/p');
	if [[ "$1" == "" ]]; then
		script_name=run_all_plru.pss
	else
		script_name=run_all_plru_"$1".pss;
	fi;
    file_path=../../fpga_proxy/scripts/;
    rm -f "$file_path"/"$script_name";
    for i in *;
    do
    	if [[ "$i" != "deriche" || ("$i" == "deriche" && "$variant" != *"large") ]]; then
	    	if [[ "$1" != "" ]]; then
	            echo RUN ../benchmarks/SHEL_"$1"/"$i"/program >> "$file_path"/"$script_name";
	        else
	        	echo RUN ../benchmarks/SHEL/"$i"/program >> "$file_path"/"$script_name";
	        fi
	   fi
    done
}



(cd ../../benchmarks/SHEL/ && make_run_all_plru_script)
(cd ../../benchmarks/SHEL_medium/ && make_run_all_plru_script medium)
(cd ../../benchmarks/SHEL_large/ && make_run_all_plru_script large)
(cd ../../benchmarks/CLAM/ && make_benchmarks  && make_run_all_script && make_track_all_script)
(cd ../../benchmarks/SHEL/ && make_benchmarks && make_run_all_script && make_track_all_script)
(cd ../../benchmarks/C-SHEL/ && make_benchmarks && make_run_all_script && make_track_all_script)
(cd ../../benchmarks/PRL/ && make_benchmarks && make_run_all_script && make_track_all_script)
(cd ../../benchmarks/CLAM_medium/ && make_benchmarks  && make_run_all_script && make_track_all_script) 
(cd ../../benchmarks/SHEL_medium/ && make_benchmarks && make_run_all_script && make_track_all_script)
(cd ../../benchmarks/C-SHEL_medium/ && make_benchmarks && make_run_all_script && make_track_all_script)
(cd ../../benchmarks/PRL_medium/ && make_benchmarks && make_run_all_script && make_track_all_script)
#(cd ../../benchmarks/CLAM_large/ && make_benchmarks  && make_run_all_script && make_track_all_script#) 
#(cd ../../benchmarks/SHEL_large/ && make_benchmarks && make_run_all_script && make_track_all_script) 
#(cd ../../benchmarks/C-SHEL_large/ && make_benchmarks && make_run_all_script && make_track_all_script) 
#(cd ../../benchmarks/PRL_large/ && make_benchmarks && make_run_all_script && make_track_all_script)
# #(cd ../../benchmarks/CLAM_extra_large/ && make_benchmarks  && make_run_all_script && make_track_all_script) 
# #(cd ../../benchmarks/SHEL_extra_large/ && make_benchmarks && make_run_all_script && make_track_all_script) 
# #(cd ../../benchmarks/C-SHEL_extra_large/ && make_benchmarks && make_run_all_script && make_track_all_script) 
# #(cd ../../benchmarks/PRL_extra_large/ && make_benchmarks && make_run_all_script && make_track_all_script)
